config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resource :user, only: [:new,:create,:show]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user # ビューで使えるようにする

  def login? # ログインしているか確かめるメソッド
    if current_user.nil? # current_userがnilの時
      redirect_to login_path, alert: "ログインしてください。"
    end
  end

  def already_login?
    unless current_user.nil?
      redirect_to user_path, notice: "ログインしています。"
    end
  end

  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # ユーザーのパスワードとあっていたら
    if user && user.authenticate(params[:password])
      # セッションにアクセスできる データを格納している cookieに保存されている
      session[:user_id] = user.id
      redirect_to user_path, notice: "ログインに成功しました。"
    else
      flash.now[:alert] = "メールアドレスもしくはパスワードが間違っています。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "ログアウトに成功しました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new,:create]
  before_action :login?,only: :show
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to user_path, notice: "登録に成功しています。"
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>こんにちは!</h1>

<%= link_to "サインアップ", new_user_path %>
<%= link_to "ログイン", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>サインアップ</h1>

<%= form_with model: @user, url: user_path, local: true do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "サインアップ"%>
  </div>
  <%= link_to "ログイン", login_path%>
<%end%>

app/views/users/show.html.erb
<h1>詳細</h1>
<p><%= current_user.email %></p>
<%= link_to "ログアウト", logout_path, method: :delete %>